#!/bin/bash

echo "Operating System: $OSTYPE"

if [[ "$OSTYPE" == "linux-gnu"* ]] || [[ "$OSTYPE" == "darwin"* ]];
then
    # Linux or Mac OSX
    sourcePath="nvim/"
    destinationPath="$HOME/.config/nvim"
elif [[ "$OSTYPE" == "msys" ]];
then
    # Windows
    sourcePath="nvim\\"
    destinationPath="$USERPROFILE\\AppData\\Local\\"
else
    # Unknown.
    echo "Unknown OS, exiting."
    exit 1
fi

echo "Source Path: $sourcePath"
echo "Destination Path: $destinationPath"

cp -rf "$sourcePath" "$destinationPath"
